version: "3.9"
services:
  backend:
    image: ghcr.io/${GITHUB_REPOSITORY}/student-grade-backend:latest
    restart: unless-stopped
    env_file:
      - ./backend.env
    ports:
      - "3001:3001"
    networks:
      - app

networks:
  app:
    driver: bridge
