name: Backend - Build & Deploy

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
      - ".github/workflows/backend-render.yml"
  workflow_dispatch:

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present
        env:
          NODE_ENV: production

  deploy:
    name: Trigger Render Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via Render Deploy Hook
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" -X POST "$RENDER_DEPLOY_HOOK" | tee http_status.txt
          CODE=$(cat http_status.txt)
          if [ "$CODE" -lt 200 ] || [ "$CODE" -ge 300 ]; then
            echo "Render deploy hook failed with status $CODE" >&2
            exit 1
          fi
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

